<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ferm</string>
	</array>
	<key>name</key>
	<string>ferm</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#includes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#actions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#chains</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interfaces</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#defines</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#modules</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#proto</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ips</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>actions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ferm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Z]+);</string>
		</dict>
		<key>chains</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.ferm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ferm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(chain)\s+([A-Z]+)</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.ferm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#.*)</string>
		</dict>
		<key>defines</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ferm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@def)\s+</string>
		</dict>
		<key>includes</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ferm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.ferm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@include)\s+('[\w\.\/_-]+')</string>
		</dict>
		<key>interfaces</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.ferm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ferm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(interface|outerface)\s+([a-z0-9]+|\$[A-Za-z][A-Za-z0-9_]+)?</string>
		</dict>
		<key>ips</key>
		<dict>
			<key>match</key>
			<string>(?:[0-9]{1,3}\.){3}[0-9]{1,3}</string>
			<key>name</key>
			<string>constant.numeric.ferm</string>
		</dict>
		<key>modules</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ferm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.ferm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.ferm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(mod)\s+(\w+)\s+([\w-]+)</string>
		</dict>
		<key>proto</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ferm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.ferm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.ferm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(proto)\s+(\w+)\s+</string>
		</dict>
		<key>variables</key>
		<dict>
			<key>match</key>
			<string>\$[A-Za-z][A-Za-z0-9_]+</string>
			<key>name</key>
			<string>variable.parameter.ferm</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ferm</string>
	<key>uuid</key>
	<string>bbe827dd-77a7-4cb8-816c-c3ae79fd2add</string>
</dict>
</plist>
